name: distributed-system

services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  kafka:
    image: redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "1G"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command:
      - start-dev
      - --import-realm
      - --proxy-headers=xforwarded
      - --hostname-debug=true
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: /keycloak
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 80
      KC_HOSTNAME_STRICT: "false"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro

  users:
    build:
      context: ../services/users
    environment:
      SERVER_PORT: 8083
      KEYCLOAK_ADMIN_BASE_URL: http://keycloak:8080/keycloak
      KEYCLOAK_ADMIN_REALM: demo
      KEYCLOAK_ADMIN_ADMIN_REALM: master
      KEYCLOAK_ADMIN_USERNAME: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - rabbitmq
      - kafka

  orders:
    build:
      context: ../services/orders
    environment:
      SERVER_PORT: 8082
    depends_on:
      - rabbitmq
      - kafka
      - users

  notifications:
    build:
      context: ../services/notifications
    environment:
      SERVER_PORT: 8081
    depends_on:
      - kafka
      - redis

  worker:
    build:
      context: ../services/worker
    environment:
      SERVER_PORT: 8084
      FAAS_FN_BASE_URL: http://host.docker.internal:12345
      FAAS_FN_APP: soa
      FAAS_FN_FUNCTION_NAME: order-fn
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - rabbitmq

  gateway-1:
    build:
      context: ../services/gateway
    environment:
      SERVER_PORT: 8080
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost/keycloak/realms/demo
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/keycloak/realms/demo/protocol/openid-connect/certs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - keycloak
      - orders
      - users

  orders-mf:
    build:
      context: ../web/orders-mf
    ports:
      - "5171:80"

  users-mf:
    build:
      context: ../web/users-mf
    ports:
      - "5172:80"

  notifications-mf:
    build:
      context: ../web/notifications-mf
    ports:
      - "5173:80"

  shell:
    build:
      context: ../web/shell
      args:
        VITE_REMOTE_ORDERS: /remotes/orders/assets/remoteEntry.js
        VITE_REMOTE_USERS: /remotes/users/assets/remoteEntry.js
        VITE_REMOTE_NOTIFICATIONS: /remotes/notifications/assets/remoteEntry.js
    ports:
      - "5170:80"
    depends_on:
      - orders-mf
      - users-mf
      - notifications-mf

  gateway-2:
    build:
      context: ../services/gateway
    environment:
      SERVER_PORT: 8080
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost/keycloak/realms/demo
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/keycloak/realms/demo/protocol/openid-connect/certs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - keycloak
      - orders
      - users

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - gateway-1
      - gateway-2

volumes:
  pgdata:
