server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  application:
    name: users

keycloak:
  admin:
    base-url: http://keycloak:8080/keycloak
    realm: demo
    admin-realm: master
    username: admin
    password: admin
